name: Code and Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  code-scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Sonar Scanner
      run: npm install -g sonar-scanner

    - name: Run SonarQube Scan
      run: |
        sonar-scanner \
          -Dsonar.projectKey=my-website-project \
          -Dsonar.organization=my-org \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.sources=./ \
          -Dsonar.language=js,html,css \
          -Dsonar.sourceEncoding=UTF-8
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  security-scan:
    name: Trivy File Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Trivy
      uses: aquasecurity/trivy-action@v0.28.0
      with:
        scan-type: 'filesystem'
        severity: 'HIGH,CRITICAL'
        output: 'trivy-results.json'
        format: 'json'

    - name: Upload Trivy Report
      uses: actions/upload-artifact@v3
      with:
        name: trivy-results
        path: trivy-results.json

  build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
         docker build -t user-ui:${{ github.run_number }} .

    - name: Run Trivy vulnerability scanner on Docker image
      uses: aquasecurity/trivy-action@0.28.0
      continue-on-error: true
      with:
          image-ref: 'user-ui'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          
    - name: Push Docker Image
      run: |
        docker tag user-ui:${{ github.run_number }} ${{ vars.DOCKER_USERNAME }}/user-ui:v19
        docker push ${{ vars.DOCKER_USERNAME }}/user-ui:v19