name: SonarQube Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Set the desired Node.js version

    - name: Install Sonar Scanner
      run: npm install -g sonar-scanner

    - name: Run SonarQube Scan
      run: |
        sonar-scanner \
          -Dsonar.projectKey=my-website-project \
          -Dsonar.organization=my-org \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.sources=./ \
          -Dsonar.language=js,html,css \
          -Dsonar.sourceEncoding=UTF-8
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
